---
title: "Homework5_613"
author: "Elizabeth Marge"
date: "2/26/2021"
output: word_document
---

```{r}

Stockreturns <- c(-8.36,   1.63,  -2.27, -2.93,  -2.70, 
                           -2.93, -9.14, -2.64, 6.82,   -2.35, 
                           -3.58,   6.13,   7.00, -15.25, -8.66,
                           -1.03, -9.16,  -1.25, -1.22,  -10.27,
                           -5.11, -0.80,  -1.44,  1.28,  -0.65,
                            4.34,   12.22, -7.21, -0.09, 7.34, 
                            5.04,  -7.24,  -2.14, -1.01,  -1.41, 
                            12.03, -2.53,  4.33,  1.35)
Stockreturns

```

## 1

```{r}

mean(Stockreturns)

```
## 2 

```{r}

sd(Stockreturns)

```
## 3

```{r}

pnorm(-1.5, mean=-1.124615, sd=5.977673, lower.tail = TRUE)

```
## 4

```{r}

pnorm(.70, mean=-1.124615, sd=5.977673, lower.tail = FALSE)

```

## 5


```{r}

summary(Stockreturns)

## The 1st Quartile is -3.255. 

```

## 6

```{r}

## Checks for outliers 

boxplot(Stockreturns)

## There are a few outliers shown within the boxplot.


```


```{r}

# Check the qq plots for normality
qqnorm(Stockreturns)

## In checking normality, this shows a normal plot with a positive correlation.

```

## 7

```{r}

## The average of the S&P 500 stock index for the same period was 0.95%. Does the broker perform worse than average? 

## Null- H0 = .95
## Alternative- Ha < .95
  
```

## 8

```{r}

t.test(Stockreturns, mu = .95,  alternative = "less")

## p-value = 0.1237
## confidence interval is between -Inf 0.4891698
```

## 9

```{r}

## Now answer the question originally stated.  Does the broker perform worse than average? (Explain or justify in two or three sentences)


## Since the p-value of 0.01827 and is greater than .05 at 95% confidence, we reject the null hypothesis that the average is equal to .95. In addition, Since the number .95 is not in the confidence interval of  -Inf 0.4891698, this supports the claim that we reject the null hypothesis. 

```
