---
title: "Lab_March24"
author: "Elizabeth Marge"
date: "3/24/2021"
output: word_document
---

```{r}

library(tidyverse)
library(dplyr)
library(data.table)


```


```{r}

flights1 <- fread("nyc14.csv")
flights1

```

```{r}

flights2 <- read_csv("nyc14.csv") # produces a tibble
flights2
  
class(flights2)

```


## Question 1 


```{r}


flights1[, .(year, month, day, hour)]


```

## Question 2


```{r}

flights1[origin == "JFK" & dest == "SEA" & carrier=="DL"]

```


## Question 3 

```{r}

flights1 %>% filter(air_time< 330, month=="3", carrier=="UA")


```


##  Question 4 

```{r}

flights1 %>%
  select(carrier, month, air_time)%>%
  filter(carrier == "UA", month == 3, air_time < 330)
```

## Question 5 

```{r}

##  5) Use the data.table method to add a variable called speed that is the average air speed of the plane in miles per hour. 

flights1[,c("speed"):= .(distance / hour)]
flights1



```


## Question 6

```{r}

## 6) Use the tidyverse method to add a variable called speed that is the average air speed of the plane in miles per hour.

flights2 %>%
  mutate(mph = (distance/hour))



```
## Question 7 

```{r}

## 7) Show and use coding to change the carrier abbreviation of UA to UniitedAir

flights1

flights1[carrier == "UA", carrier := "UnitedAir"]
flights1

```

```{r}

## (7) Show and use coding to change the carrier abbreviation of UA to UniitedAir

flights2 %>%
  mutate(carrier = recode(carrier, "UA" = "UnitedAir")) ->
  flights2
flights2

View(flights2)


```
